package elabuelonicolas.bd.domain;

public class Cliente {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Cliente.id
	 * @mbg.generated  Mon Apr 30 16:43:23 CDT 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Cliente.nombre
	 * @mbg.generated  Mon Apr 30 16:43:23 CDT 2018
	 */
	private String nombre;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Cliente.direccion
	 * @mbg.generated  Mon Apr 30 16:43:23 CDT 2018
	 */
	private String direccion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Cliente.contacto
	 * @mbg.generated  Mon Apr 30 16:43:23 CDT 2018
	 */
	private String contacto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Cliente.telefono
	 * @mbg.generated  Mon Apr 30 16:43:23 CDT 2018
	 */
	private String telefono;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Cliente.rfc
	 * @mbg.generated  Mon Apr 30 16:43:23 CDT 2018
	 */
	private String rfc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column Cliente.email
	 * @mbg.generated  Mon Apr 30 16:43:23 CDT 2018
	 */
	private String email;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Cliente.id
	 * @return  the value of Cliente.id
	 * @mbg.generated  Mon Apr 30 16:43:23 CDT 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Cliente.id
	 * @param id  the value for Cliente.id
	 * @mbg.generated  Mon Apr 30 16:43:23 CDT 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Cliente.nombre
	 * @return  the value of Cliente.nombre
	 * @mbg.generated  Mon Apr 30 16:43:23 CDT 2018
	 */
	public String getNombre() {
		return nombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Cliente.nombre
	 * @param nombre  the value for Cliente.nombre
	 * @mbg.generated  Mon Apr 30 16:43:23 CDT 2018
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Cliente.direccion
	 * @return  the value of Cliente.direccion
	 * @mbg.generated  Mon Apr 30 16:43:23 CDT 2018
	 */
	public String getDireccion() {
		return direccion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Cliente.direccion
	 * @param direccion  the value for Cliente.direccion
	 * @mbg.generated  Mon Apr 30 16:43:23 CDT 2018
	 */
	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Cliente.contacto
	 * @return  the value of Cliente.contacto
	 * @mbg.generated  Mon Apr 30 16:43:23 CDT 2018
	 */
	public String getContacto() {
		return contacto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Cliente.contacto
	 * @param contacto  the value for Cliente.contacto
	 * @mbg.generated  Mon Apr 30 16:43:23 CDT 2018
	 */
	public void setContacto(String contacto) {
		this.contacto = contacto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Cliente.telefono
	 * @return  the value of Cliente.telefono
	 * @mbg.generated  Mon Apr 30 16:43:23 CDT 2018
	 */
	public String getTelefono() {
		return telefono;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Cliente.telefono
	 * @param telefono  the value for Cliente.telefono
	 * @mbg.generated  Mon Apr 30 16:43:23 CDT 2018
	 */
	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Cliente.rfc
	 * @return  the value of Cliente.rfc
	 * @mbg.generated  Mon Apr 30 16:43:23 CDT 2018
	 */
	public String getRfc() {
		return rfc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Cliente.rfc
	 * @param rfc  the value for Cliente.rfc
	 * @mbg.generated  Mon Apr 30 16:43:23 CDT 2018
	 */
	public void setRfc(String rfc) {
		this.rfc = rfc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column Cliente.email
	 * @return  the value of Cliente.email
	 * @mbg.generated  Mon Apr 30 16:43:23 CDT 2018
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column Cliente.email
	 * @param email  the value for Cliente.email
	 * @mbg.generated  Mon Apr 30 16:43:23 CDT 2018
	 */
	public void setEmail(String email) {
		this.email = email;
	}
}