package elabuelonicolas.bd.domain;

import java.util.Date;

public class Compras {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Compras.id
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Compras.idProveedor
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    private Integer idproveedor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Compras.idListaCompra
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    private Integer idlistacompra;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Compras.fecha
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    private Date fecha;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Compras.precioTotal
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    private Double preciototal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Compras.id
     *
     * @return the value of Compras.id
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Compras.id
     *
     * @param id the value for Compras.id
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Compras.idProveedor
     *
     * @return the value of Compras.idProveedor
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    public Integer getIdproveedor() {
        return idproveedor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Compras.idProveedor
     *
     * @param idproveedor the value for Compras.idProveedor
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    public void setIdproveedor(Integer idproveedor) {
        this.idproveedor = idproveedor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Compras.idListaCompra
     *
     * @return the value of Compras.idListaCompra
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    public Integer getIdlistacompra() {
        return idlistacompra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Compras.idListaCompra
     *
     * @param idlistacompra the value for Compras.idListaCompra
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    public void setIdlistacompra(Integer idlistacompra) {
        this.idlistacompra = idlistacompra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Compras.fecha
     *
     * @return the value of Compras.fecha
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    public Date getFecha() {
        return fecha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Compras.fecha
     *
     * @param fecha the value for Compras.fecha
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Compras.precioTotal
     *
     * @return the value of Compras.precioTotal
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    public Double getPreciototal() {
        return preciototal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Compras.precioTotal
     *
     * @param preciototal the value for Compras.precioTotal
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    public void setPreciototal(Double preciototal) {
        this.preciototal = preciototal;
    }
}