package elabuelonicolas.bd.domain;

public class Direccion {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column direccion.id
     *
     * @mbg.generated Tue May 29 00:37:22 CDT 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column direccion.pais
     *
     * @mbg.generated Tue May 29 00:37:22 CDT 2018
     */
    private String pais;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column direccion.ciudad
     *
     * @mbg.generated Tue May 29 00:37:22 CDT 2018
     */
    private String ciudad;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column direccion.colonia
     *
     * @mbg.generated Tue May 29 00:37:22 CDT 2018
     */
    private String colonia;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column direccion.calle
     *
     * @mbg.generated Tue May 29 00:37:22 CDT 2018
     */
    private String calle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column direccion.numero
     *
     * @mbg.generated Tue May 29 00:37:22 CDT 2018
     */
    private Integer numero;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column direccion.id
     *
     * @return the value of direccion.id
     *
     * @mbg.generated Tue May 29 00:37:22 CDT 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column direccion.id
     *
     * @param id the value for direccion.id
     *
     * @mbg.generated Tue May 29 00:37:22 CDT 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column direccion.pais
     *
     * @return the value of direccion.pais
     *
     * @mbg.generated Tue May 29 00:37:22 CDT 2018
     */
    public String getPais() {
        return pais;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column direccion.pais
     *
     * @param pais the value for direccion.pais
     *
     * @mbg.generated Tue May 29 00:37:22 CDT 2018
     */
    public void setPais(String pais) {
        this.pais = pais;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column direccion.ciudad
     *
     * @return the value of direccion.ciudad
     *
     * @mbg.generated Tue May 29 00:37:22 CDT 2018
     */
    public String getCiudad() {
        return ciudad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column direccion.ciudad
     *
     * @param ciudad the value for direccion.ciudad
     *
     * @mbg.generated Tue May 29 00:37:22 CDT 2018
     */
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column direccion.colonia
     *
     * @return the value of direccion.colonia
     *
     * @mbg.generated Tue May 29 00:37:22 CDT 2018
     */
    public String getColonia() {
        return colonia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column direccion.colonia
     *
     * @param colonia the value for direccion.colonia
     *
     * @mbg.generated Tue May 29 00:37:22 CDT 2018
     */
    public void setColonia(String colonia) {
        this.colonia = colonia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column direccion.calle
     *
     * @return the value of direccion.calle
     *
     * @mbg.generated Tue May 29 00:37:22 CDT 2018
     */
    public String getCalle() {
        return calle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column direccion.calle
     *
     * @param calle the value for direccion.calle
     *
     * @mbg.generated Tue May 29 00:37:22 CDT 2018
     */
    public void setCalle(String calle) {
        this.calle = calle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column direccion.numero
     *
     * @return the value of direccion.numero
     *
     * @mbg.generated Tue May 29 00:37:22 CDT 2018
     */
    public Integer getNumero() {
        return numero;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column direccion.numero
     *
     * @param numero the value for direccion.numero
     *
     * @mbg.generated Tue May 29 00:37:22 CDT 2018
     */
    public void setNumero(Integer numero) {
        this.numero = numero;
    }
}