package elabuelonicolas.bd.domain;

public class Listaventas {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ListaVentas.id
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ListaVentas.idProducto
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    private Integer idproducto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ListaVentas.cantidad
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    private Integer cantidad;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ListaVentas.subtotal
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    private Double subtotal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ListaVentas.id
     *
     * @return the value of ListaVentas.id
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ListaVentas.id
     *
     * @param id the value for ListaVentas.id
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ListaVentas.idProducto
     *
     * @return the value of ListaVentas.idProducto
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    public Integer getIdproducto() {
        return idproducto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ListaVentas.idProducto
     *
     * @param idproducto the value for ListaVentas.idProducto
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    public void setIdproducto(Integer idproducto) {
        this.idproducto = idproducto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ListaVentas.cantidad
     *
     * @return the value of ListaVentas.cantidad
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    public Integer getCantidad() {
        return cantidad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ListaVentas.cantidad
     *
     * @param cantidad the value for ListaVentas.cantidad
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ListaVentas.subtotal
     *
     * @return the value of ListaVentas.subtotal
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    public Double getSubtotal() {
        return subtotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ListaVentas.subtotal
     *
     * @param subtotal the value for ListaVentas.subtotal
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    public void setSubtotal(Double subtotal) {
        this.subtotal = subtotal;
    }
}