package elabuelonicolas.bd.domain;

public class Listaventa {
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column listaventa.id
	 * @mbg.generated  Thu May 31 22:35:26 CDT 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column listaventa.idventa
	 * @mbg.generated  Thu May 31 22:35:26 CDT 2018
	 */
	private Integer idventa;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column listaventa.idproducto
	 * @mbg.generated  Thu May 31 22:35:26 CDT 2018
	 */
	private Integer idproducto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column listaventa.cantidad
	 * @mbg.generated  Thu May 31 22:35:26 CDT 2018
	 */
	private Integer cantidad;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column listaventa.subtotal
	 * @mbg.generated  Thu May 31 22:35:26 CDT 2018
	 */
	private Double subtotal;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column listaventa.id
	 * @return  the value of listaventa.id
	 * @mbg.generated  Thu May 31 22:35:26 CDT 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column listaventa.id
	 * @param id  the value for listaventa.id
	 * @mbg.generated  Thu May 31 22:35:26 CDT 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column listaventa.idventa
	 * @return  the value of listaventa.idventa
	 * @mbg.generated  Thu May 31 22:35:26 CDT 2018
	 */
	public Integer getIdventa() {
		return idventa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column listaventa.idventa
	 * @param idventa  the value for listaventa.idventa
	 * @mbg.generated  Thu May 31 22:35:26 CDT 2018
	 */
	public void setIdventa(Integer idventa) {
		this.idventa = idventa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column listaventa.idproducto
	 * @return  the value of listaventa.idproducto
	 * @mbg.generated  Thu May 31 22:35:26 CDT 2018
	 */
	public Integer getIdproducto() {
		return idproducto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column listaventa.idproducto
	 * @param idproducto  the value for listaventa.idproducto
	 * @mbg.generated  Thu May 31 22:35:26 CDT 2018
	 */
	public void setIdproducto(Integer idproducto) {
		this.idproducto = idproducto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column listaventa.cantidad
	 * @return  the value of listaventa.cantidad
	 * @mbg.generated  Thu May 31 22:35:26 CDT 2018
	 */
	public Integer getCantidad() {
		return cantidad;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column listaventa.cantidad
	 * @param cantidad  the value for listaventa.cantidad
	 * @mbg.generated  Thu May 31 22:35:26 CDT 2018
	 */
	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column listaventa.subtotal
	 * @return  the value of listaventa.subtotal
	 * @mbg.generated  Thu May 31 22:35:26 CDT 2018
	 */
	public Double getSubtotal() {
		return subtotal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column listaventa.subtotal
	 * @param subtotal  the value for listaventa.subtotal
	 * @mbg.generated  Thu May 31 22:35:26 CDT 2018
	 */
	public void setSubtotal(Double subtotal) {
		this.subtotal = subtotal;
	}
}