package elabuelonicolas.bd.domain;

public class Listaventas {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column listaventas.id
	 * @mbg.generated  Sat May 05 18:38:25 CDT 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column listaventas.idProducto
	 * @mbg.generated  Sat May 05 18:38:25 CDT 2018
	 */
	private Integer idproducto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column listaventas.cantidad
	 * @mbg.generated  Sat May 05 18:38:25 CDT 2018
	 */
	private Integer cantidad;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column listaventas.subtotal
	 * @mbg.generated  Sat May 05 18:38:25 CDT 2018
	 */
	private Double subtotal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column listaventas.idVenta
	 * @mbg.generated  Sat May 05 18:38:25 CDT 2018
	 */
	private Integer idventa;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column listaventas.id
	 * @return  the value of listaventas.id
	 * @mbg.generated  Sat May 05 18:38:25 CDT 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column listaventas.id
	 * @param id  the value for listaventas.id
	 * @mbg.generated  Sat May 05 18:38:25 CDT 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column listaventas.idProducto
	 * @return  the value of listaventas.idProducto
	 * @mbg.generated  Sat May 05 18:38:25 CDT 2018
	 */
	public Integer getIdproducto() {
		return idproducto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column listaventas.idProducto
	 * @param idproducto  the value for listaventas.idProducto
	 * @mbg.generated  Sat May 05 18:38:25 CDT 2018
	 */
	public void setIdproducto(Integer idproducto) {
		this.idproducto = idproducto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column listaventas.cantidad
	 * @return  the value of listaventas.cantidad
	 * @mbg.generated  Sat May 05 18:38:25 CDT 2018
	 */
	public Integer getCantidad() {
		return cantidad;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column listaventas.cantidad
	 * @param cantidad  the value for listaventas.cantidad
	 * @mbg.generated  Sat May 05 18:38:25 CDT 2018
	 */
	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column listaventas.subtotal
	 * @return  the value of listaventas.subtotal
	 * @mbg.generated  Sat May 05 18:38:25 CDT 2018
	 */
	public Double getSubtotal() {
		return subtotal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column listaventas.subtotal
	 * @param subtotal  the value for listaventas.subtotal
	 * @mbg.generated  Sat May 05 18:38:25 CDT 2018
	 */
	public void setSubtotal(Double subtotal) {
		this.subtotal = subtotal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column listaventas.idVenta
	 * @return  the value of listaventas.idVenta
	 * @mbg.generated  Sat May 05 18:38:25 CDT 2018
	 */
	public Integer getIdventa() {
		return idventa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column listaventas.idVenta
	 * @param idventa  the value for listaventas.idVenta
	 * @mbg.generated  Sat May 05 18:38:25 CDT 2018
	 */
	public void setIdventa(Integer idventa) {
		this.idventa = idventa;
	}
}