package elabuelonicolas.bd.domain;

public class Producto {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column producto.id
	 * @mbg.generated  Tue May 29 00:37:22 CDT 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column producto.tipo
	 * @mbg.generated  Tue May 29 00:37:22 CDT 2018
	 */
	private String tipo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column producto.marca
	 * @mbg.generated  Tue May 29 00:37:22 CDT 2018
	 */
	private String marca;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column producto.costo
	 * @mbg.generated  Tue May 29 00:37:22 CDT 2018
	 */
	private String costo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column producto.existencia
	 * @mbg.generated  Tue May 29 00:37:22 CDT 2018
	 */
	private Integer existencia;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column producto.id
	 * @return  the value of producto.id
	 * @mbg.generated  Tue May 29 00:37:22 CDT 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column producto.id
	 * @param id  the value for producto.id
	 * @mbg.generated  Tue May 29 00:37:22 CDT 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column producto.tipo
	 * @return  the value of producto.tipo
	 * @mbg.generated  Tue May 29 00:37:22 CDT 2018
	 */
	public String getTipo() {
		return tipo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column producto.tipo
	 * @param tipo  the value for producto.tipo
	 * @mbg.generated  Tue May 29 00:37:22 CDT 2018
	 */
	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column producto.marca
	 * @return  the value of producto.marca
	 * @mbg.generated  Tue May 29 00:37:22 CDT 2018
	 */
	public String getMarca() {
		return marca;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column producto.marca
	 * @param marca  the value for producto.marca
	 * @mbg.generated  Tue May 29 00:37:22 CDT 2018
	 */
	public void setMarca(String marca) {
		this.marca = marca;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column producto.costo
	 * @return  the value of producto.costo
	 * @mbg.generated  Tue May 29 00:37:22 CDT 2018
	 */
	public String getCosto() {
		return costo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column producto.costo
	 * @param costo  the value for producto.costo
	 * @mbg.generated  Tue May 29 00:37:22 CDT 2018
	 */
	public void setCosto(String costo) {
		this.costo = costo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column producto.existencia
	 * @return  the value of producto.existencia
	 * @mbg.generated  Tue May 29 00:37:22 CDT 2018
	 */
	public Integer getExistencia() {
		return existencia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column producto.existencia
	 * @param existencia  the value for producto.existencia
	 * @mbg.generated  Tue May 29 00:37:22 CDT 2018
	 */
	public void setExistencia(Integer existencia) {
		this.existencia = existencia;
	}
}