package elabuelonicolas.bd.domain;

public class Producto {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column producto.id
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column producto.tipo
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	private String tipo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column producto.marca
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	private String marca;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column producto.costocompra
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	private Double costocompra;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column producto.costoventa
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	private Double costoventa;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column producto.existencia
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	private Integer existencia;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column producto.status
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	private Integer status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column producto.id
	 * @return  the value of producto.id
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column producto.id
	 * @param id  the value for producto.id
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column producto.tipo
	 * @return  the value of producto.tipo
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public String getTipo() {
		return tipo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column producto.tipo
	 * @param tipo  the value for producto.tipo
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column producto.marca
	 * @return  the value of producto.marca
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public String getMarca() {
		return marca;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column producto.marca
	 * @param marca  the value for producto.marca
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public void setMarca(String marca) {
		this.marca = marca;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column producto.costocompra
	 * @return  the value of producto.costocompra
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public Double getCostocompra() {
		return costocompra;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column producto.costocompra
	 * @param costocompra  the value for producto.costocompra
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public void setCostocompra(Double costocompra) {
		this.costocompra = costocompra;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column producto.costoventa
	 * @return  the value of producto.costoventa
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public Double getCostoventa() {
		return costoventa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column producto.costoventa
	 * @param costoventa  the value for producto.costoventa
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public void setCostoventa(Double costoventa) {
		this.costoventa = costoventa;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column producto.existencia
	 * @return  the value of producto.existencia
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public Integer getExistencia() {
		return existencia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column producto.existencia
	 * @param existencia  the value for producto.existencia
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public void setExistencia(Integer existencia) {
		this.existencia = existencia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column producto.status
	 * @return  the value of producto.status
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column producto.status
	 * @param status  the value for producto.status
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}
}