package elabuelonicolas.bd.domain;

public class Producto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Producto.id
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Producto.tipo
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    private String tipo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Producto.marca
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    private String marca;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Producto.costo
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    private String costo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Producto.existencia
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    private Integer existencia;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Producto.id
     *
     * @return the value of Producto.id
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Producto.id
     *
     * @param id the value for Producto.id
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Producto.tipo
     *
     * @return the value of Producto.tipo
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    public String getTipo() {
        return tipo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Producto.tipo
     *
     * @param tipo the value for Producto.tipo
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Producto.marca
     *
     * @return the value of Producto.marca
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    public String getMarca() {
        return marca;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Producto.marca
     *
     * @param marca the value for Producto.marca
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    public void setMarca(String marca) {
        this.marca = marca;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Producto.costo
     *
     * @return the value of Producto.costo
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    public String getCosto() {
        return costo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Producto.costo
     *
     * @param costo the value for Producto.costo
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    public void setCosto(String costo) {
        this.costo = costo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Producto.existencia
     *
     * @return the value of Producto.existencia
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    public Integer getExistencia() {
        return existencia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Producto.existencia
     *
     * @param existencia the value for Producto.existencia
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    public void setExistencia(Integer existencia) {
        this.existencia = existencia;
    }
}