package elabuelonicolas.bd.domain;

public class Proveedor {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column proveedor.id
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column proveedor.nombre
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	private String nombre;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column proveedor.contacto
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	private String contacto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column proveedor.telefono
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	private String telefono;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column proveedor.email
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column proveedor.rfc
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	private String rfc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column proveedor.estado
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	private String estado;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column proveedor.municipio
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	private String municipio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column proveedor.localidad
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	private String localidad;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column proveedor.codigopostal
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	private Integer codigopostal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column proveedor.asentamiento
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	private String asentamiento;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column proveedor.calle
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	private String calle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column proveedor.numero
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	private Integer numero;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column proveedor.status
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	private Integer status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column proveedor.id
	 * @return  the value of proveedor.id
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column proveedor.id
	 * @param id  the value for proveedor.id
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column proveedor.nombre
	 * @return  the value of proveedor.nombre
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public String getNombre() {
		return nombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column proveedor.nombre
	 * @param nombre  the value for proveedor.nombre
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column proveedor.contacto
	 * @return  the value of proveedor.contacto
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public String getContacto() {
		return contacto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column proveedor.contacto
	 * @param contacto  the value for proveedor.contacto
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public void setContacto(String contacto) {
		this.contacto = contacto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column proveedor.telefono
	 * @return  the value of proveedor.telefono
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public String getTelefono() {
		return telefono;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column proveedor.telefono
	 * @param telefono  the value for proveedor.telefono
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column proveedor.email
	 * @return  the value of proveedor.email
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column proveedor.email
	 * @param email  the value for proveedor.email
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column proveedor.rfc
	 * @return  the value of proveedor.rfc
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public String getRfc() {
		return rfc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column proveedor.rfc
	 * @param rfc  the value for proveedor.rfc
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public void setRfc(String rfc) {
		this.rfc = rfc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column proveedor.estado
	 * @return  the value of proveedor.estado
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public String getEstado() {
		return estado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column proveedor.estado
	 * @param estado  the value for proveedor.estado
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public void setEstado(String estado) {
		this.estado = estado;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column proveedor.municipio
	 * @return  the value of proveedor.municipio
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public String getMunicipio() {
		return municipio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column proveedor.municipio
	 * @param municipio  the value for proveedor.municipio
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public void setMunicipio(String municipio) {
		this.municipio = municipio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column proveedor.localidad
	 * @return  the value of proveedor.localidad
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public String getLocalidad() {
		return localidad;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column proveedor.localidad
	 * @param localidad  the value for proveedor.localidad
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public void setLocalidad(String localidad) {
		this.localidad = localidad;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column proveedor.codigopostal
	 * @return  the value of proveedor.codigopostal
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public Integer getCodigopostal() {
		return codigopostal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column proveedor.codigopostal
	 * @param codigopostal  the value for proveedor.codigopostal
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public void setCodigopostal(Integer codigopostal) {
		this.codigopostal = codigopostal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column proveedor.asentamiento
	 * @return  the value of proveedor.asentamiento
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public String getAsentamiento() {
		return asentamiento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column proveedor.asentamiento
	 * @param asentamiento  the value for proveedor.asentamiento
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public void setAsentamiento(String asentamiento) {
		this.asentamiento = asentamiento;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column proveedor.calle
	 * @return  the value of proveedor.calle
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public String getCalle() {
		return calle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column proveedor.calle
	 * @param calle  the value for proveedor.calle
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public void setCalle(String calle) {
		this.calle = calle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column proveedor.numero
	 * @return  the value of proveedor.numero
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public Integer getNumero() {
		return numero;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column proveedor.numero
	 * @param numero  the value for proveedor.numero
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public void setNumero(Integer numero) {
		this.numero = numero;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column proveedor.status
	 * @return  the value of proveedor.status
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column proveedor.status
	 * @param status  the value for proveedor.status
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}
}