package elabuelonicolas.bd.domain;

public class Proveedor {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column proveedor.id
	 * @mbg.generated  Thu May 31 22:35:26 CDT 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column proveedor.nombre
	 * @mbg.generated  Thu May 31 22:35:26 CDT 2018
	 */
	private String nombre;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column proveedor.iddireccion
	 * @mbg.generated  Thu May 31 22:35:26 CDT 2018
	 */
	private Integer iddireccion;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column proveedor.contacto
	 * @mbg.generated  Thu May 31 22:35:26 CDT 2018
	 */
	private String contacto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column proveedor.telefono
	 * @mbg.generated  Thu May 31 22:35:26 CDT 2018
	 */
	private String telefono;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column proveedor.email
	 * @mbg.generated  Thu May 31 22:35:26 CDT 2018
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column proveedor.rfc
	 * @mbg.generated  Thu May 31 22:35:26 CDT 2018
	 */
	private String rfc;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column proveedor.id
	 * @return  the value of proveedor.id
	 * @mbg.generated  Thu May 31 22:35:26 CDT 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column proveedor.id
	 * @param id  the value for proveedor.id
	 * @mbg.generated  Thu May 31 22:35:26 CDT 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column proveedor.nombre
	 * @return  the value of proveedor.nombre
	 * @mbg.generated  Thu May 31 22:35:26 CDT 2018
	 */
	public String getNombre() {
		return nombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column proveedor.nombre
	 * @param nombre  the value for proveedor.nombre
	 * @mbg.generated  Thu May 31 22:35:26 CDT 2018
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column proveedor.iddireccion
	 * @return  the value of proveedor.iddireccion
	 * @mbg.generated  Thu May 31 22:35:26 CDT 2018
	 */
	public Integer getIddireccion() {
		return iddireccion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column proveedor.iddireccion
	 * @param iddireccion  the value for proveedor.iddireccion
	 * @mbg.generated  Thu May 31 22:35:26 CDT 2018
	 */
	public void setIddireccion(Integer iddireccion) {
		this.iddireccion = iddireccion;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column proveedor.contacto
	 * @return  the value of proveedor.contacto
	 * @mbg.generated  Thu May 31 22:35:26 CDT 2018
	 */
	public String getContacto() {
		return contacto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column proveedor.contacto
	 * @param contacto  the value for proveedor.contacto
	 * @mbg.generated  Thu May 31 22:35:26 CDT 2018
	 */
	public void setContacto(String contacto) {
		this.contacto = contacto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column proveedor.telefono
	 * @return  the value of proveedor.telefono
	 * @mbg.generated  Thu May 31 22:35:26 CDT 2018
	 */
	public String getTelefono() {
		return telefono;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column proveedor.telefono
	 * @param telefono  the value for proveedor.telefono
	 * @mbg.generated  Thu May 31 22:35:26 CDT 2018
	 */
	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column proveedor.email
	 * @return  the value of proveedor.email
	 * @mbg.generated  Thu May 31 22:35:26 CDT 2018
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column proveedor.email
	 * @param email  the value for proveedor.email
	 * @mbg.generated  Thu May 31 22:35:26 CDT 2018
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column proveedor.rfc
	 * @return  the value of proveedor.rfc
	 * @mbg.generated  Thu May 31 22:35:26 CDT 2018
	 */
	public String getRfc() {
		return rfc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column proveedor.rfc
	 * @param rfc  the value for proveedor.rfc
	 * @mbg.generated  Thu May 31 22:35:26 CDT 2018
	 */
	public void setRfc(String rfc) {
		this.rfc = rfc;
	}
}