package elabuelonicolas.bd.domain;

public class Proveedor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Proveedor.id
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Proveedor.nombre
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    private String nombre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Proveedor.direccion
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    private String direccion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Proveedor.contacto
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    private String contacto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Proveedor.telefono
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    private String telefono;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Proveedor.rfc
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    private String rfc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Proveedor.email
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Proveedor.id
     *
     * @return the value of Proveedor.id
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Proveedor.id
     *
     * @param id the value for Proveedor.id
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Proveedor.nombre
     *
     * @return the value of Proveedor.nombre
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    public String getNombre() {
        return nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Proveedor.nombre
     *
     * @param nombre the value for Proveedor.nombre
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Proveedor.direccion
     *
     * @return the value of Proveedor.direccion
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    public String getDireccion() {
        return direccion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Proveedor.direccion
     *
     * @param direccion the value for Proveedor.direccion
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Proveedor.contacto
     *
     * @return the value of Proveedor.contacto
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    public String getContacto() {
        return contacto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Proveedor.contacto
     *
     * @param contacto the value for Proveedor.contacto
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    public void setContacto(String contacto) {
        this.contacto = contacto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Proveedor.telefono
     *
     * @return the value of Proveedor.telefono
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    public String getTelefono() {
        return telefono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Proveedor.telefono
     *
     * @param telefono the value for Proveedor.telefono
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Proveedor.rfc
     *
     * @return the value of Proveedor.rfc
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    public String getRfc() {
        return rfc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Proveedor.rfc
     *
     * @param rfc the value for Proveedor.rfc
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    public void setRfc(String rfc) {
        this.rfc = rfc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Proveedor.email
     *
     * @return the value of Proveedor.email
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Proveedor.email
     *
     * @param email the value for Proveedor.email
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }
}