package elabuelonicolas.bd.domain;

import java.util.Date;

public class Ventas {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ventas.id
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ventas.idCliente
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    private Integer idcliente;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ventas.idListaVenta
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    private Integer idlistaventa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ventas.fecha
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    private Date fecha;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Ventas.precioTotal
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    private Double preciototal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ventas.id
     *
     * @return the value of Ventas.id
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ventas.id
     *
     * @param id the value for Ventas.id
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ventas.idCliente
     *
     * @return the value of Ventas.idCliente
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    public Integer getIdcliente() {
        return idcliente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ventas.idCliente
     *
     * @param idcliente the value for Ventas.idCliente
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    public void setIdcliente(Integer idcliente) {
        this.idcliente = idcliente;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ventas.idListaVenta
     *
     * @return the value of Ventas.idListaVenta
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    public Integer getIdlistaventa() {
        return idlistaventa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ventas.idListaVenta
     *
     * @param idlistaventa the value for Ventas.idListaVenta
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    public void setIdlistaventa(Integer idlistaventa) {
        this.idlistaventa = idlistaventa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ventas.fecha
     *
     * @return the value of Ventas.fecha
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    public Date getFecha() {
        return fecha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ventas.fecha
     *
     * @param fecha the value for Ventas.fecha
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Ventas.precioTotal
     *
     * @return the value of Ventas.precioTotal
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    public Double getPreciototal() {
        return preciototal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Ventas.precioTotal
     *
     * @param preciototal the value for Ventas.precioTotal
     *
     * @mbg.generated Mon Apr 30 16:43:23 CDT 2018
     */
    public void setPreciototal(Double preciototal) {
        this.preciototal = preciototal;
    }
}