package elabuelonicolas.bd.domain;

import java.sql.Date;

public class Venta {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column venta.id
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column venta.idcliente
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	private Integer idcliente;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column venta.fecha
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	private Date fecha;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column venta.total
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	private Double total;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column venta.totalreal
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	private Double totalreal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column venta.ganancia
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	private Double ganancia;
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column venta.ganancia
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	private String nombre;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column venta.id
	 * @return  the value of venta.id
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column venta.id
	 * @param id  the value for venta.id
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column venta.idcliente
	 * @return  the value of venta.idcliente
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public Integer getIdcliente() {
		return idcliente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column venta.idcliente
	 * @param idcliente  the value for venta.idcliente
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public void setIdcliente(Integer idcliente) {
		this.idcliente = idcliente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column venta.fecha
	 * @return  the value of venta.fecha
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public Date getFecha() {
		return fecha;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column venta.fecha
	 * @param fecha  the value for venta.fecha
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column venta.total
	 * @return  the value of venta.total
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public Double getTotal() {
		return total;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column venta.total
	 * @param total  the value for venta.total
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public void setTotal(Double total) {
		this.total = total;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column venta.totalreal
	 * @return  the value of venta.totalreal
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public Double getTotalreal() {
		return totalreal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column venta.totalreal
	 * @param totalreal  the value for venta.totalreal
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public void setTotalreal(Double totalreal) {
		this.totalreal = totalreal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column venta.ganancia
	 * @return  the value of venta.ganancia
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public Double getGanancia() {
		return ganancia;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column venta.ganancia
	 * @param ganancia  the value for venta.ganancia
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public void setGanancia(Double ganancia) {
		this.ganancia = ganancia;
	}
	
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column venta.ganancia
	 * @return  the value of venta.ganancia
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public String getNombre() {
		return nombre;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column venta.ganancia
	 * @param ganancia  the value for venta.ganancia
	 * @mbg.generated  Thu Jun 14 19:38:42 CDT 2018
	 */
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
}