package elabuelonicolas.bd.domain;

import java.util.Date;

public class Venta {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column venta.id
	 * @mbg.generated  Thu May 31 22:35:26 CDT 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column venta.idcliente
	 * @mbg.generated  Thu May 31 22:35:26 CDT 2018
	 */
	private Integer idcliente;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column venta.fecha
	 * @mbg.generated  Thu May 31 22:35:26 CDT 2018
	 */
	private Date fecha;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column venta.total
	 * @mbg.generated  Thu May 31 22:35:26 CDT 2018
	 */
	private Double total;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column venta.id
	 * @return  the value of venta.id
	 * @mbg.generated  Thu May 31 22:35:26 CDT 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column venta.id
	 * @param id  the value for venta.id
	 * @mbg.generated  Thu May 31 22:35:26 CDT 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column venta.idcliente
	 * @return  the value of venta.idcliente
	 * @mbg.generated  Thu May 31 22:35:26 CDT 2018
	 */
	public Integer getIdcliente() {
		return idcliente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column venta.idcliente
	 * @param idcliente  the value for venta.idcliente
	 * @mbg.generated  Thu May 31 22:35:26 CDT 2018
	 */
	public void setIdcliente(Integer idcliente) {
		this.idcliente = idcliente;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column venta.fecha
	 * @return  the value of venta.fecha
	 * @mbg.generated  Thu May 31 22:35:26 CDT 2018
	 */
	public Date getFecha() {
		return fecha;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column venta.fecha
	 * @param fecha  the value for venta.fecha
	 * @mbg.generated  Thu May 31 22:35:26 CDT 2018
	 */
	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column venta.total
	 * @return  the value of venta.total
	 * @mbg.generated  Thu May 31 22:35:26 CDT 2018
	 */
	public Double getTotal() {
		return total;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column venta.total
	 * @param total  the value for venta.total
	 * @mbg.generated  Thu May 31 22:35:26 CDT 2018
	 */
	public void setTotal(Double total) {
		this.total = total;
	}
}